# pull official base image
FROM python:3.11.4-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ../requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY .. /usr/src/app

# Formato linux
RUN sed -i 's/\r$//g' /usr/src/app/docker/dev/entrypoint.dev.sh

# Otorgamos todos los permisos al archivo entrypoint
RUN chmod a+x /usr/src/app/docker/dev/entrypoint.dev.sh

# Otorgamos todos los permisos al archivo entrypoint
RUN chmod a+r /usr/src/app/docker/dev/entrypoint.dev.sh

# run entrypoint.sh
ENTRYPOINT ["./docker/dev/entrypoint.dev.sh"]