version: '3.8'

services:
  web:
    build:
      context: ../../../CMS
      dockerfile: docker/dev/Dockerfile.dev
    command: bash docker/dev/entrypoint.dev.sh
    volumes:
      - ../../../CMS:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - 5434:5432
volumes:
  postgres_data:
