# Generated by Django 4.2.5 on 2023-09-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('crear_contenido', 'Crear contenido'), ('editar_contenido', 'Editar contenido'), ('publicar_contenido', 'Publicar contenido')),
                'default_permissions': (),
            },
        ),
    ]
