# Generated by Django 4.2.4 on 2023-08-22 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NombreModelo",
            new_name="Contenido",
        ),
        migrations.AlterModelOptions(
            name="contenido",
            options={"permissions": (("Crear contenido", "Permite crear contenido"),)},
        ),
    ]
