# Generated by Django 4.2.4 on 2023-08-22 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0002_rename_nombremodelo_contenido_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contenido",
            options={"permissions": (("crear_contenido", "Crear contenido"),)},
        ),
    ]
