# Generated by Django 4.2.5 on 2023-09-29 22:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_contenido_autor_contenido_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, default='cuerpo'),
        ),
    ]
