# Generated by Django 4.2.5 on 2023-09-30 03:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_alter_contenido_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(default='cuerpo'),
        ),
    ]
