# Generated by Django 4.2.5 on 2023-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_contenido_numero_valoraciones_contenido_puntuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='estado',
            field=models.CharField(default='Borrador', max_length=30),
        ),
    ]
