# Generated by Django 4.2.5 on 2023-11-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipoContenido', '0001_initial'),
        ('contenido', '0008_contenido_numero_vistas_alter_contenido_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoContenido.tipocontenido'),
        ),
    ]
