# Generated by Django 4.2.5 on 2023-12-01 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenido', '0011_alter_contenido_tipo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
