# Generated by Django 4.2.5 on 2023-11-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoContenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontenido',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
