# Generated by Django 4.2.5 on 2023-09-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("permiso", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, unique=True)),
                ("descripcion", models.CharField(max_length=100)),
                ("permisos", models.ManyToManyField(to="permiso.permiso")),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "rol",
            },
        ),
    ]
