# Generated by Django 4.2.5 on 2023-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_rol_last_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
