version: '3.8'

services:
  web:
    build:
      context: ../../../CMS
      dockerfile: docker/prod/Dockerfile.prod
    command: gunicorn CMS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5433:5432
  nginx:
    build: ../../nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  # nginx y web comparten el volumen para que se le pueda proveer a nginx los archivos estaticos
  static_volume:
