# Generated by Django 4.2.5 on 2023-09-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categorias', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
