# Generated by Django 4.2.5 on 2023-09-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "permiso",
            },
        ),
    ]
