# Generated by Django 4.2.5 on 2023-09-23 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permiso", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permiso",
            name="descripcion",
        ),
    ]
